spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: ${MAIL_HOST}
            enable: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DB_URL}
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}